
# use an official OpenJDK runtime as the base image 
FROM eclipse-temurin:11-jdk

# set the working directory to /app
WORKDIR /app

#copy the Spring Boot application JAR file into the container
COPY target/ORSProject-10-0.0.1-SNAPSHOT.jar /ORSProject-10-0.0.1-SNAPSHOT.jar

# expose port 8080 for the application
EXPOSE 8080

# define the command to run the Spring Boot application 
ENTRYPOINT ["java","-jar","ORSProject-10-0.0.1-SNAPSHOT.jar"]